### ISSUE TITLE
Wrong Fragment Manager

### ISSUE THREAD

**Issue by arieftb** [rizkirchm97/Movie-Catalogue#1]
https://github.com/rizkirchm97/Movie-Catalogue/blob/5e08beebee887cac1f87858ee1c40d516e9f284c/app/src/main/java/com/rizki/moviecatalogue/ui/favourite/FavouriteFragment.kt#L33

Must use childFragmentManager  instead of fragmentManager if you want to show your fragment inside of the fragment.

**Comment by rizkirchm97** [comment]
thanks for taking the time to analyze the bug and help fix it
